// default package
// Generated Jan 14, 2023, 8:48:57 PM by Hibernate Tools 6.1.6.Final
package iti.jets;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments"
    ,catalog="employees"
    , uniqueConstraints = @UniqueConstraint(columnNames="dept_name") 
)
public class Departments  implements java.io.Serializable {


     private String deptNo;
     private String deptName;
     private Set<DeptEmp> deptEmps = new HashSet<DeptEmp>(0);
     private Set<DeptManager> deptManagers = new HashSet<DeptManager>(0);

    public Departments() {
    }

	
    public Departments(String deptNo, String deptName) {
        this.deptNo = deptNo;
        this.deptName = deptName;
    }
    public Departments(String deptNo, String deptName, Set<DeptEmp> deptEmps, Set<DeptManager> deptManagers) {
       this.deptNo = deptNo;
       this.deptName = deptName;
       this.deptEmps = deptEmps;
       this.deptManagers = deptManagers;
    }
   
     @Id 

    
    @Column(name="dept_no", unique=true, nullable=false, length=4)
    public String getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    
    @Column(name="dept_name", unique=true, nullable=false, length=40)
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<DeptEmp> getDeptEmps() {
        return this.deptEmps;
    }
    
    public void setDeptEmps(Set<DeptEmp> deptEmps) {
        this.deptEmps = deptEmps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<DeptManager> getDeptManagers() {
        return this.deptManagers;
    }
    
    public void setDeptManagers(Set<DeptManager> deptManagers) {
        this.deptManagers = deptManagers;
    }




}


