// default package
// Generated Jan 14, 2023, 8:48:57 PM by Hibernate Tools 6.1.6.Final
package iti.jets;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * DeptEmpId generated by hbm2java
 */
@Embeddable
public class DeptEmpId  implements java.io.Serializable {


     private String deptNo;
     private int empNo;

    public DeptEmpId() {
    }

    public DeptEmpId(String deptNo, int empNo) {
       this.deptNo = deptNo;
       this.empNo = empNo;
    }
   


    @Column(name="dept_no", nullable=false, length=4)
    public String getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }


    @Column(name="emp_no", nullable=false)
    public int getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeptEmpId) ) return false;
		 DeptEmpId castOther = ( DeptEmpId ) other; 
         
		 return ( (this.getDeptNo()==castOther.getDeptNo()) || ( this.getDeptNo()!=null && castOther.getDeptNo()!=null && this.getDeptNo().equals(castOther.getDeptNo()) ) )
 && (this.getEmpNo()==castOther.getEmpNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDeptNo() == null ? 0 : this.getDeptNo().hashCode() );
         result = 37 * result + this.getEmpNo();
         return result;
   }   


}


